<?php
/**
 * Theme index file
 *
 * @package    Baseless
 * @subpackage Admin
 * @category   Themes
 * @since      1.0.0
 */

// Alias namespaces.
use CMS\{
	Tags as Tags,
	Admin_Tags as Admin
};

// Maybe get minified assets.
$suffix = '.min';
if ( defined( 'DEBUG_MODE' ) && DEBUG_MODE ) {
	$suffix = '';
}

?>
<!DOCTYPE html>
<html dir="auto" class="no-js" lang="<?php echo $L->currentLanguageShortVersion(); ?>" xmlns:og="http://opengraphprotocol.org/schema/">
<head>
	<title><?php echo $layout['title']; ?></title>

	<meta charset="<?php echo CHARSET; ?>" />
	<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
	<meta name="robots" content="noindex,nofollow" />

	<?php

	// Change `<html>` 'no-js' class to 'js' if JavaScript is enabled.
	echo "<script>(function(html){html.className = html.className.replace(/\bno-js\b/,'js')})(document.documentElement);</script>\n"; ?>

	<!-- Favicon -->
	<link rel="shortcut icon" type="image/x-icon" href="<?php echo HTML_PATH_CORE_IMG . 'favicon.png?version=' . CMS_VERSION; ?>">

	<link rel="stylesheet" type="text/css" href="<?php echo DOMAIN_ADMIN_THEME; ?>assets/css/bootstrap.min.css?version=<?php echo CMS_VERSION; ?>">
	<link rel="stylesheet" type="text/css" href="<?php echo DOMAIN_CORE_CSS; ?>line-awesome/css/line-awesome-font-awesome.min.css?version=<?php echo CMS_VERSION; ?>">
	<?php
		echo Theme :: css( [
			'style.css'
		], DOMAIN_ADMIN_THEME . 'assets/css/' );
		echo Theme :: css( array(
			'jquery.datetimepicker.min.css',
			'select2.min.css',
			'select2-bootstrap4.min.css'
		), DOMAIN_ADMIN_THEME . 'assets/css/' );
	?>

	<?php
		Tags\jquery();
		echo Theme :: jsBootstrap();
		echo Theme :: jsSortable();
		echo Theme :: js( array(
			'jquery.datetimepicker.full.min.js',
			'select2.full.min.js',
			'functions.js'
		), DOMAIN_CORE_JS, null );
	?>

	<?php Theme :: plugins( 'adminHead' ); ?>

</head>
<body>

<?php Theme :: plugins( 'adminBodyBegin' ); ?>

<!-- Javascript dynamic generated by PHP -->
<?php
	echo '<script charset="utf-8">' . PHP_EOL;
	include( PATH_BOOT . 'js-variables.php' );
	echo '</script>' . PHP_EOL;

	echo '<script charset="utf-8">' . PHP_EOL;
	include( PATH_CORE_JS . 'ajax.php' );
	echo '</script>' . PHP_EOL;
?>

<!-- Overlay background -->
<div id="jsshadow"></div>

<?php include( 'views/alert.php' ); ?>

<?php // include( 'views/navbar.php' ); ?>

<div id="admin-page">

	<div id="admin-menu">
		<?php include( 'views/menu.php' ); ?>
	</div>

	<div id="admin-content">
	<?php Admin\admin_content(); ?>
	</div>
</div>

<?php Theme :: plugins( 'adminBodyEnd' ); ?>

</body>
</html>
